# Form implementation generated from reading ui file '.\GUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 584)
        MainWindow.setMinimumSize(QtCore.QSize(800, 550))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QFrame {\n"
"    background-color: rgb(90, 90, 90);\n"
"    color: white;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(parent=self.mainFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit{\n"
"    color: rgb(0, 255, 0);\n"
"}")
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout.addWidget(self.mainFrame)
        self.optionFrame = QtWidgets.QFrame(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.optionFrame.setFont(font)
        self.optionFrame.setStyleSheet("QCheckBox {\n"
"    color: white;\n"
"    padding: 10px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 25px;\n"
"    height: 25px;\n"
"}\n"
"")
        self.optionFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.optionFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.optionFrame.setObjectName("optionFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.optionFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.optionGrid = QtWidgets.QGridLayout()
        self.optionGrid.setObjectName("optionGrid")
        self.prefetch = QtWidgets.QCheckBox(parent=self.optionFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.prefetch.setFont(font)
        self.prefetch.setObjectName("prefetch")
        self.optionGrid.addWidget(self.prefetch, 1, 0, 1, 1)
        self.appLogs = QtWidgets.QCheckBox(parent=self.optionFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.appLogs.setFont(font)
        self.appLogs.setObjectName("appLogs")
        self.optionGrid.addWidget(self.appLogs, 1, 1, 1, 1)
        self.systemTemp = QtWidgets.QCheckBox(parent=self.optionFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.systemTemp.setFont(font)
        self.systemTemp.setObjectName("systemTemp")
        self.optionGrid.addWidget(self.systemTemp, 0, 1, 1, 1)
        self.logFiles = QtWidgets.QCheckBox(parent=self.optionFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.logFiles.setFont(font)
        self.logFiles.setObjectName("logFiles")
        self.optionGrid.addWidget(self.logFiles, 2, 0, 1, 1)
        self.tempFiles = QtWidgets.QCheckBox(parent=self.optionFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.tempFiles.setFont(font)
        self.tempFiles.setObjectName("tempFiles")
        self.optionGrid.addWidget(self.tempFiles, 0, 0, 1, 1)
        self.updateLogs = QtWidgets.QCheckBox(parent=self.optionFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.updateLogs.setFont(font)
        self.updateLogs.setStyleSheet("")
        self.updateLogs.setObjectName("updateLogs")
        self.optionGrid.addWidget(self.updateLogs, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.optionGrid)
        self.pushButton = QtWidgets.QPushButton(parent=self.optionFrame)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    margin-top: 50px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 391, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.optionFrame)
        self.horizontalLayout.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:12pt; font-weight:700; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">=====================</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">GrowTimizer</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Windows Automated Cleaner</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Created By NetCat_</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">V.1.0.0</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">=====================</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.prefetch.setText(_translate("MainWindow", "Prefetch"))
        self.appLogs.setText(_translate("MainWindow", "AppLogs"))
        self.systemTemp.setText(_translate("MainWindow", "System Temp"))
        self.logFiles.setText(_translate("MainWindow", "Log Files"))
        self.tempFiles.setText(_translate("MainWindow", "Temp Files"))
        self.updateLogs.setText(_translate("MainWindow", "Update Logs"))
        self.pushButton.setText(_translate("MainWindow", "Run"))
